version: "2"
run:
  go: "1.22"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - ginkgolinter
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
      no-unaliased: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: bool-literal-in-expr
        - name: constant-logical-expr
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: 'G108: Profiling endpoint is automatically exposed on /debug/pprof'
      - linters:
          - revive
        text: 'exported: exported method .*\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported'
      - linters:
          - errcheck
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - staticcheck
        text: 'SA1019: .*The component config package has been deprecated and will be removed in a future release.'
      - linters:
          - staticcheck
        text: 'SA1019: workqueue.(RateLimitingInterface|DefaultControllerRateLimiter|New|NewItemExponentialFailureRateLimiter|NewRateLimitingQueueWithConfig|DefaultItemBasedRateLimiter|RateLimitingQueueConfig) is deprecated:'
      - linters:
          - revive
        source: _ "embed"
      - linters:
          - revive
        text: exported (method|function|type|const) (.+) should have comment or be unexported
        source: (func|type).*Fake.*
      - linters:
          - revive
        path: fake_\.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - unparam
        text: always receives
      - path: _test\.go
        text: should not use dot imports
      - path: _test\.go
        text: cyclomatic complexity
      - path: _test\.go
        text: 'G107: Potential HTTP request made with variable url'
      - linters:
          - gocritic
        text: 'appendAssign: append result not assigned to the same slice'
      - linters:
          - gocritic
        text: 'singleCaseSwitch: should rewrite switch statement to if statement'
      - linters:
          - gosec
        text: 'G304: Potential file inclusion via variable'
      - linters:
          - dupl
          - errcheck
          - goconst
        path: _test\.go
      - path: (.+)\.go$
        text: Subprocess launch(ed with variable|ing should be audited)
      - path: (.+)\.go$
        text: (G204|G104|G307)
      - path: (.+)\.go$
        text: 'ST1000: at least one file in a package should have a package comment'
    paths:
      - zz_generated.*\.go$
      - .*conversion.*\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - .*conversion.*\.go$
      - third_party$
      - builtin$
      - examples$
